[package]
edition = "2021"
name = "rucaptcha"
version = "3.0.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
image = "0.24.4"
imageproc = "0.23.0"
magnus = "0.4"
rand = "0.8.5"
rusttype = "0.9.2"
lazy_static = "1.4.0"
